### ISSUE TITLE
Reader may not run sequentially.

### ISSUE THREAD

**Issue by OperationMech** [elopez7590/Project-Spring2016#4]
#2

Needs to be done.

**Comment by OperationMech** [comment]
Working on this currently, may have a preliminary solution.

**Comment by elopez7590** [comment]
Hi Anthony,

I'm working on my part right now and will probably push something later
tonight.

I'd like to see you next weekend Sunday so we can wrap this project up.
I'll talk to you more about it tomorrow.

Thanks
Edde Lopez
