### ISSUE TITLE
Jar execution.

### ISSUE THREAD

**Issue by OperationMech** [elopez7590/Project-Spring2016#5]
It seems that maven is not generating the MANIFEST.MF file correctly.

**Comment by elopez7590** [comment]
Hi Anthony,

Was this solved?

I'll try to help work on those Java Servlets tonight. I'm just stressed
right now with my new job plus the fact that I earlier this week already
accepted an offer from another company where I think I can perform better
than where I am now and I've been filling out several forms with that other
company.

Thanks
Edde Lopez
